### ISSUE TITLE
Security issue Yaml

### ISSUE THREAD

**Issue by BigslimVdub** [Karbovanets/karbo-nodes-map#6]
Please check out security patch for package-lock.json: 

https://github.com/AEONCommunity/aeon-shell-map/commit/687a3c1499ca0ea445692af935f8fb6254880b55

https://github.com/AEONCommunity/aeon-shell-map/blob/master/package-lock.json

**Comment by Looongcat** [comment]
That repo doesn't use js-yaml, other dependencies will be updated to the latest stable versions soon
